### ISSUE TITLE
[Share] Share button does not work on Firefox

### ISSUE THREAD

**Issue by sebez** [KleeGroup/focus-showcase#15]
## Actual behaviour

On Chrome, the card share button opens an email with the component link => OK :+1: 

![share](https://cloud.githubusercontent.com/assets/9380855/10606402/e11a1e46-7732-11e5-83d5-2d151c9b113b.jpg)

On Firefox, it has no effect. => KO :-1: 
## Expected behaviour

The share button should work in all major browsers like a recent Firefox.

**Comment by pierr** [comment]
This seems to be a browser related issue see https://support.mozilla.org/en-US/kb/change-program-used-open-email-links#w_setting-firefoxs-mail-client in order to set the default 'mailto://' application

**Comment by pierr** [comment]
I had the same issue on chrome

**Comment by pierr** [comment]
Please reopen it if this does not fix your problem.
